name: sdfr
channels:
  - nodefaults
  - pytorch
  - nvidia
  - thombashi
  - conda-forge
dependencies:
  - python<3.11
  - pip
  - numpy
  - scipy
  - pandas
  - opencv>=4.8
  - pytorch-cuda=11.8
  - pytorch>=2.1,<2.2
  - torchvision>=0.16
  - deepface
  - aiohttp
  - aiodns
  - tqdm
  - submitit
  - pathvalidate
  - torchmetrics
  - lightning
  - wandb
  - graph-tool
  - pip:
      - facenet-pytorch
      - albumentations --no-binary qudida,albumentations
      - onnx
      - onnxruntime-gpu
      - jsonargparse[signatures]
      - omegaconf
